config/routes.rb
Rails.application.routes.draw do
  root to: "users#show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users, only: [:show]
  resources :links, only: [:create, :edit, :update]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :links, only: [:update]
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :url, presence: true, url: true
  belongs_to :user

  scope :order_by_creation, -> { order(created_at: :desc) }

  def status
    read ? "read" : "unread"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :links
  validates :email, uniqueness: true, presence: true
  validates :password, confirmation: true
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    protect_from_forgery with: :null_session
    respond_to :json
  end
end

app/controllers/api/v1/links_controller.rb
module Api
  module V1
    class LinksController < ApiController
      def update
        link = Link.find(params[:id])
        if link.update(link_params)
          respond_with(link, status: 200, location: user_path(current_user.id))
        else
          render json: link.errors, status: 422
        end
      end

      private
        def link_params
          params.require(:link).permit(:title, :url, :read)
        end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :must_login

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def must_login
    if !current_user
      redirect_to login_path
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def create
    link = current_user.links.build(link_params)
    if link.save
      flash[:info] = "#{link.title} has been created"
    else
      flash[:error] = "Please provide a valid URL"
    end
    redirect_to user_path(current_user)
  end

  private

  def link_params
    params.require(:link).permit(:url, :title, :status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect to login_path
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :must_login, only: [:show]

  def show
    @links = current_user.links
    @link = Link.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to signup_path
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spinboard</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body>
  <% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "alert-#{type}" %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for(@user, url: signup_path) do |f| %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit "Submit" %>
  </p>

<% end  %>

app/views/users/show.html.erb
<div class="container">
  <section class="col-xs-6">
    <p>Welcome, <%= current_user.email %></p>
    <p>
      <%= link_to "Logout", logout_path %>
    </p>

    <h2>
      Add a new link
    </h2>

    <section class="new_link">
      <%= form_for(@link) do |f| %>
        <p>
          <%= f.text_field :url, placeholder: "Link URL" %>
        </p>
        <p>
          <%= f.text_field :title, placeholder: "Title" %>
        </p>
        <p>
          <%= f.submit "Submit Link", class: "btn btn-default" %>
        </p>
      <% end %>
    </section>

    <form>
      <label class="sr-only" for="search"></label>
      <input type="text" class="form-control" id="filterLinks" placeholder="Filter Links">
    </form>

    <%= button_tag "Show Read", id: "filterRead", class: "btn-default" %>
    <%= button_tag "Show Unread", id: "filterUnread", class: "btn-default" %>
    <%= button_tag "Sort Alphabetically", id: "sortAlpha", class: "btn-default"%>

  </section>

  <section class=" col-xs-6">
    <h2>Your Links</h2>
    <div class="allLinks">
      <% @links.all.each do |link| %>
        <div data-id="<%= link.id%>" class="eachLink">
          <% readStatus = "read" if link.read %>
          <p class="<%= readStatus  %>">
            <%= link_to link.title, link.url, class: "linkTitle" %>
          </p>
          <p>
            <a href="#" class="markAsRead <%= "hidden" if link.read %>">(Mark as read)</a>
            <a href="#" class="markAsUnread <%= "hidden" if !link.read %>">(Mark as unread)</a>
            <%= link_to "(Edit)", edit_link_path(link), method: "get" %>
          </p>
        </div>
      <% end %>
    </div>
  </section>
</div